### PR TITLE
added type annotations to parser

### PR DESCRIPTION
**Pull request by yogthos**
Hi Dan,

I profiled Clabango and added type annotations to functions that were showing up high on CPU usage. A lot of it was caused by reflection calls. After adding the annotations the usage drops significantly.

### CODE REVIEW

**Comment by danlarkin** [comment]
Could you contribute a test to show these are necessary/sufficient? Otherwise we can never be sure about the performance implications of a change.

**Comment by yogthos** [comment]
Sure thing. I'll make a project for benchmarking then and get you some actual data. :) It would probably be useful to have going forward as well.

**Comment by danlarkin** [comment]
If you want to keep it in this project that's okay with me too, that way it's easy to test for performance regressions when making experimental changes. We can use lein test-selectors to only run the (presumably slow) performance regression tests when necessary.

**Comment by yogthos** [comment]
Sounds good, and then we can just run the existing tests already defined. I'll update the pull request once I have it all done. :)

**Comment by yogthos** [comment]
So, good news the benchmarks are now in and they're turned off by default. I'm not actually noticing the benefit from the annotations when running them though. So, maybe I'll take them out from this commit.

The way I tested last time was using jvisualvm and the reflection calls were showing up quite a bit. Looks like that doesn't necessarily mean it's a problem once it warms up though.

**Comment by danlarkin** [comment]
I wonder if rather than benchmarking each test in `clabango.test.parser` it would be better to come up with one/two/a handful of tests that are representative of real world templates.

Like one test that goes through several layers of inheritance with complicated block overriding logic.

Maybe another that uses lots of nested `for` loops with template includes inside or something like that.

Using tests like that will let us better (though still probably not accurately) gauge how future changes (or annotations et al.) effect performance.

**Comment by yogthos** [comment]
Yeah I think that's a good idea. Going through the parser tests might still be handy for seeing regressions as well. Could setup another lein selector for that. The benchmarking only lets us see the current performance though.

I think profiling by hand is the only way to see what the actual bottlenecks are though. It might be worth running one of these complex benchmarks with jvisualvm attached and see what the profiler says.

Do you want to try come up with some of the real world benchmarks or should I give it a shot? :)

**Comment by danlarkin** [comment]
It'd be rad if you gave it a shot :) I've got some ideas around (optionally) caching disk reads and template lexing which should (I think?) improve performance, if only because of the saved IO.

**Comment by yogthos** [comment]
Cool, I'll try cook something up then. :)

**Comment by yogthos** [comment]
I added a more representative template configuration for the benchmark, let me know what you think. :)

and there is an improvement using annotations with this benchmark:

without annotations

```
benchmarking: site
WARNING: Final GC required 16.05983028996469 % of runtime
Evaluation count : 12 in 6 samples of 2 calls.
             Execution time mean : 54.436083 ms
    Execution time std-deviation : 672.294634 us
   Execution time lower quantile : 53.765500 ms ( 2.5%)
   Execution time upper quantile : 55.259375 ms (97.5%)
```

with annotations

```
benchmarking: site
WARNING: Final GC required 16.81953493913444 % of runtime
Evaluation count : 18 in 6 samples of 3 calls.
             Execution time mean : 34.506833 ms
    Execution time std-deviation : 235.437748 us
   Execution time lower quantile : 34.291333 ms ( 2.5%)
   Execution time upper quantile : 34.877500 ms (97.5%)
```

**Comment by danlarkin** [comment]
Hey so I changed this a little and removed the testing of individual functions. I don't really see the purpose of that, and I don't want to have to remember to add all new tests to that list.

I tried to do some profiling with and without the annotations you added, but I think my yourkit-fu isn't advanced enough to understand what I was seeing, and the benchmarks showed such a tiny gain that I'd just as well leave out the code clutter.

Let me know if you're satisfied with what I've merged.

**Comment by yogthos** [comment]
Hey, sounds good. I agree that the individual function tests are probably not that useful. I haven't tried yourkit so can't tell how that one does it. With jvisualvm you can pick a process and check the sampler. It will show you what functions are using the most cpu time. 

But yeah I agree that improvement is pretty marginal, so I think it'll be nice to just have the benchmarking code in for now.

**Comment by danlarkin** [comment]
Yes it is nice, now I can measure how much "real world" effect my lexer caching change will have, huzzah!

**Comment by yogthos** [comment]
looking forward to seeing it :)

**Pull request merged**
