### PR TITLE
HTML escaping, don't read the description.

### PR DESCRIPTION
**Pull request by bitemyapp**
I herd u like templates so I put a template library in your template library so you can template while you template.

Sorry about the hiccup thing. I know it's jack-ass ridiculous but I didn't want to "steal" a 4 line function. WHAT IF REEVES UPDATES IT?!

### CODE REVIEW

**Comment by ddillinger** [comment]
stare

**Comment by danlarkin** [comment]
Yeah I donno I'm not convinced auto escaping is necessary I guess. Is there something written up somewhere that concisely explains why it's a good idea?

Worthiness aside, there's now way I'm adding hiccup as a dependency solely for its escaping function. Surely the logic is easy enough to reproduce... or, even better, it's somewhere in an apache library?

**Comment by bitemyapp** [comment]
Hiccup is no longer in the project.clj

Please merge this, I can't recommend Clabango to anybody unless it auto-escapes.

**Comment by yogthos** [comment]
fwiw I think it would certainly help prevent attacks and would mean the user doesn't have to worry about it. Maybe it could be set as a flag so that it can be turned off if not desired?

**Comment by bitemyapp** [comment]
As long as auto-escaping is the default I'd be quite satisfied with this.

**Comment by bitemyapp** [comment]
Mumble mumble security, XSS mumble mumble.

It's the default behavior in virtually every other templating language in existence.

**Comment by bitemyapp** [comment]
Tests pass, it's a small and unintrusive addition

**Comment by danlarkin** [comment]
This change makes the to-json filter useless though, since it's going to get escaped after being encoded. What should be done here?

**Comment by bitemyapp** [comment]
1. Add a test for the to-json filter, verify that it breaks.
2. Fix the test
   a. Add a "safe" filter to shut off/reverse escaping
   b. Make to-json apply "safe"
   c. Verify JSON is JSON'y and that the test now passes

**Comment by yogthos** [comment]
also, @bitemyapp forgot to add as-str for escape-html :)

``` clojure
(defn ^String as-str
  "Converts its arguments into a string using to-str."
  [& xs]
  (apply str (map to-str xs)))
```

which I don't think is necessary in this case as the body is a string already?

so can probably just use text in escape-html

``` clojure
(defn escape-html
  "Change special characters into HTML character entities."
  [text]
  (.. ^String text
    (replace "&"  "&amp;")
    (replace "<"  "&lt;")
    (replace ">"  "&gt;")
    (replace "\"" "&quot;")))
```

**Comment by danlarkin** [comment]
I'm not satisfied with @yogthos' solution of hardcoding the `to-json` filter to be exempt from escaping. I like @bitemyapp's suggestion of having a `safe` filter, and having `to-json` set the "safe bit".

Since template filters return strings right now, there's no way to have them return a safe bit (or not) _and_ the string, since we can't put metadata on Strings. I'm thinking about changing the return value from template filters to a map like `{:string "foo" :safe true/false}`. What do y'all think?

**Comment by yogthos** [comment]
I think that's a really good idea and would make it easier to add other metadata in the future if the need arises.
Do you think the escape flag implementation would still be useful?

**Comment by bitemyapp** [comment]
I think the proposed map implementation is perfect.

**Comment by danlarkin** [comment]
Fixed in 3a14f03328fc68ec99da62e5772fadd3ac5e962c, thanks for opening this issue and working with me on finding the right solution.

Also in order to make the `safe` filter work I had to add filter chaining, so now that's a thing too :)

**Comment by yogthos** [comment]
this is very cool :)

**Comment by bitemyapp** [comment]
:heart:

**Pull request closed without merging**
