### PR TITLE
support for else condition in if tags

### PR DESCRIPTION
**Pull request by yogthos**
This seems to work without being too much of a hack hopefully :)

### CODE REVIEW

**Comment by danlarkin** [comment]
Hey this is great! Thanks for taking the time to look through my code to add this.

Unfortunately this strategy of handling `else` means that `{% else %}` becomes valid anywhere in the template, not just in an `if`. Of course I understand why you added an `else` template tag (because otherwise `parse-tags` will throw an exception) but I don't particularly like the tradeoff. Do you have any ideas on how to avoid creating `else` as its own tag? Probably involving parser pipeline refactoring...

**Comment by yogthos** [comment]
Actually, that one is a really easy fix. :) I just updated the `else` tag as follows:

``` clojure
(deftemplatetag "else" [nodes context]
  (throw (new Exception "else tag must be enclosed within an if tag"))
  {:nodes [{:type :noop}]
   :context context})
```

Since the `if` tag strips out all the `else` tags the exception will only be caused if the `else` tag is free floating. Added a test for that as well. :)

**Comment by yogthos** [comment]
updated the ifequal tags to support else for consistency

**Comment by yogthos** [comment]
@danlarkin out of curiosity, any plans to push out v0.5 on clojars soon? I kind of want to start using the `else` bit in my project :)

**Comment by danlarkin** [comment]
I just released 0.5 with your `else` support inside, thanks!

**Comment by yogthos** [comment]
fantastic :)

**Pull request merged**
